<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'
import { Download, Share2, X } from 'lucide-vue-next'
const props = defineProps<{ days: number; saved: number; currency: string }>()
const emit = defineEmits<{ close: [] }>()
const canvas = ref<HTMLCanvasElement>()
const draw = async () => { await nextTick(); const c = canvas.value; if (!c) return; const ctx = c.getContext('2d'); if (!ctx) return; const g = ctx.createLinearGradient(0, 0, 1080, 1350); g.addColorStop(0, '#087fdc'); g.addColorStop(1, '#5ab1f4'); ctx.fillStyle = g; ctx.fillRect(0, 0, c.width, c.height); ctx.fillStyle = 'rgba(255,255,255,.12)'; ctx.beginPath(); ctx.arc(1000, 1230, 260, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = 'rgba(255,255,255,.18)'; ctx.beginPath(); ctx.arc(870, 260, 115, 0, Math.PI * 2); ctx.fill(); ctx.fillStyle = '#fff'; ctx.font = '700 44px Arial'; ctx.fillText('SMOKE FREE', 78, 115); ctx.fillStyle = 'rgba(255,255,255,.76)'; ctx.font = '500 32px Arial'; ctx.fillText('МОЙ ПУТЬ БЕЗ ДЫМА', 78, 230); ctx.fillStyle = '#fff'; ctx.font = '800 174px Arial'; ctx.fillText(String(Math.max(0, Math.floor(props.days))), 72, 430); ctx.font = '600 56px Arial'; ctx.fillText('дней чистоты', 80, 510); ctx.fillStyle = 'rgba(255,255,255,.18)'; ctx.roundRect(72, 635, 936, 240, 38); ctx.fill(); ctx.fillStyle = 'rgba(255,255,255,.72)'; ctx.font = '600 32px Arial'; ctx.fillText('СОХРАНЕНО', 118, 715); ctx.fillStyle = '#fff'; ctx.font = '800 82px Arial'; ctx.fillText(`${Math.floor(props.saved).toLocaleString('ru-RU')} ${props.currency}`, 118, 815); ctx.fillStyle = 'rgba(255,255,255,.8)'; ctx.font = '500 34px Arial'; ctx.fillText('Сегодня я выбираю себя.', 78, 1175); ctx.font = '600 31px Arial'; ctx.fillText('smokefree', 78, 1250) }
onMounted(draw)
const blob = () => new Promise<Blob | null>(resolve => canvas.value?.toBlob(resolve, 'image/png'))
const share = async () => { const image = await blob(); if (!image) return; const file = new File([image], 'smokefree-achievement.png', { type: 'image/png' }); if (navigator.share && navigator.canShare?.({ files: [file] })) { await navigator.share({ title: 'Мой SmokeFree стрик', text: `${Math.floor(props.days)} дней без курения`, files: [file] }); return }; download(image) }
const download = (image?: Blob) => { const source = image ? URL.createObjectURL(image) : canvas.value?.toDataURL('image/png'); if (!source) return; const a = document.createElement('a'); a.href = source; a.download = 'smokefree-achievement.png'; a.click(); if (image) URL.revokeObjectURL(source) }
</script>
<template><div class="sheet-backdrop" @click.self="emit('close')"><section class="sheet share-sheet"><div class="sheet-handle"/><div class="sheet-title"><h2>Карточка достижения</h2><button @click="emit('close')"><X/></button></div><canvas ref="canvas" width="1080" height="1350" class="share-canvas"/><p>Создано локально на устройстве. Выбери, как поделиться достижением.</p><div class="share-actions"><button class="primary" @click="share"><Share2 :size="19"/> Поделиться</button><button class="secondary-share" @click="download()"><Download :size="19"/> PNG</button></div></section></div></template>